services:
  - type: web
    name: nefab-5s-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 4 --timeout 60
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
